# Generated by Django 3.1.2 on 2020-10-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_company_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_assets',
            old_name='c_id',
            new_name='company_id',
        ),
    ]
