# Generated by Django 3.1.2 on 2020-10-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201031_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_assets',
            old_name='company_id',
            new_name='company_ids',
        ),
    ]
