# Generated by Django 2.2.12 on 2020-11-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20201031_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_assets',
            name='company_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyasset', to='stocks.Company'),
        ),
    ]
