# Generated by Django 2.2.12 on 2020-11-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20201101_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Client')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Company')),
            ],
        ),
    ]
