# Generated by Django 2.2.12 on 2020-11-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_ipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipo',
            old_name='c_id',
            new_name='company_id',
        ),
    ]
