# Generated by Django 2.2.12 on 2020-11-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20201101_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_assets',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ipo',
            name='id',
        ),
        migrations.AlterField(
            model_name='company_assets',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='companyasset', serialize=False, to='stocks.Company'),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.Company'),
        ),
    ]
