# Generated by Django 2.2.12 on 2020-11-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20201101_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Company')),
                ('Seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Client')),
            ],
        ),
    ]
