# Generated by Django 2.2.12 on 2020-11-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
