# Generated by Django 2.2.12 on 2020-11-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Company')),
                ('Seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('Buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Client')),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Company')),
                ('Seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Market')),
            ],
        ),
    ]
